### ISSUE TITLE
a frontend widget to fetch duplicities from graph

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/similarity-finder#6]
In case duplicities do not end up in the catalogue backend, we can add js-widget on the UI which fetches duplicities from an API in the backend, the UI will then display if the record is available in which source repositories

request:

```sql
select sources from record where id = doi:10.1100/abcde
```

response

```yaml
source:
  - name: zenodo
    id: 12345
  - id: cordis
    id: 234455
```
